customhost = "database-1.cmfeax1sc1o5.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "oKzmjYcIbQXajbemJnE3"
customdb = "tcs_employee"
custombucket = "tcs-employees-bucket"
customregion = "us-east-1"
